import { GameState } from "./GameTypes";

export const initialState: GameState = {
  currentDay: 1,
  currentMonth: 1,
  balance: 5000,
  stamina: 100,
  history: [],
  workDays: 0,
  totalWorkDays: 0,
  gameOverReason: null,
  payNotification: null,
  staminaWarning: null,
  balanceWarning: null,
  MAX_MONTHS: 3,
  DAYS_IN_MONTH: 5,
  MAX_BALANCE: 5000,
  nextSalary: 0,
  isGameOver: false,
  currentChoices: [],
  
  selectChoicesForToday: () => {},
  setCurrentDay: () => {},
  setCurrentMonth: () => {},
  setBalance: () => {},
  setStamina: () => {},
  setHistory: () => {},
  setWorkDays: () => {},
  setTotalWorkDays: () => {},
  setGameOverReason: () => {},
  setPayNotification: () => {},
  setStaminaWarning: () => {},
  setBalanceWarning: () => {},
  addToHistory: () => {},
  resetWorkDays: () => {},
  calculateSalary: () => 0,
  updateMaxBalance: () => {},
  clearNotifications: () => {},
  resetGame: () => {},
};
